server:
  port: 8111

# BallCat 相关配置
ballcat:
  security:
    oauth2:
      resourceserver:
        # 不共享 token
        shared-stored-token: false
        # 不透明令牌远程自省
        opaque-token:
          client-id: test
          client-secret: test
          introspection-uri: http://127.0.0.1:8110/oauth2/introspect
        # 支持匿名登陆的 url 列表
        ignore-urls:
          /public/**


logging:
  level:
    root: debug