spring:
  datasource:
    url: jdbc:mysql://ballcat-mysql:3306/ballcat?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
  redis:
    host: ballcat-redis
    password: ''
    port: 6379


springdoc:
  swagger-ui:
    urls:
      - { name: 'admin', url: '/v3/api-docs' }
      - { name: 'api', url: 'http://ballcat-api/v3/api-docs' }
