spring:
  datasource:
    url: jdbc:mysql://ballcat-mysql:3306/ballcat?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
  redis:
    host: ballcat-redis
    password: ''
    port: 6379
  mail:
    host: smtp.qq.com
    port: 465
    username: xxxx@foxmail.com
    password: xxxxxx
    default-encoding: UTF-8
    properties:
      from: BallCat<xxxx@foxmail.com>
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

# 日志文件地址，配置此属性以便 SBA 在线查看日志
logging:
  file:
    path: logs/@artifactId@
    name: ${logging.file.path}/output.log

# 生产环境关闭文档
ballcat:
  openapi:
    enabled: false
  oss:
    endpoint: http://oss-cn-shanghai.aliyuncs.com
    access-key: xxxxx
    access-secret: xxxxx
    bucket: xxxx