server:
  port: 8110


logging:
  level:
    root: debug

# 测试共享 token 的时候需要使用实际的数据库
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/ballcat?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: '123456'