logging:
  level:
    root: debug

server:
  port: 8800


spring:
  thymeleaf:
    cache: false # 关闭缓存，否则切换测试页面会有问题
#spring:
#  redis:
#    host: ballcat-redis
#    password: ''
#    port: 6369

ballcat:
  websocket:
    concurrent:
      enable: true
      send-time-limit: 5000
      buffer-size-limit: 102400
      overflow-strategy: terminate
    with-sockjs: true
    #allowed-origins: '/ws'
    message-distributor: local