# 项目端口号
server:
  port: 9090

# 当前激活配置，默认dev
spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@
  boot:
    admin:
      client:
        url: http://ballcat-monitor:9999
        username: admin
        password: 123456

# 暴露监控端口
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 定时任务相关
xxl:
  job:
    admin:
      addresses: http://ballcat-job:8888/xxl-job-admin # xxl-job-admin 接口地址
    executor:
      port: 9091 #通讯端口
      appName: ballcat-api-job
      logretentiondays: 30 #日志保留天数

ballcat:
  security:
    oauth2:
      resourceserver:
        shared-stored-token: false
        opaque-token:
          client-id: test
          client-secret: test
          introspection-uri: http://ballcat-admin:8080/oauth/check_token
        ignore-urls:
          ## 忽略鉴权的 url 列表
          - /public/**
          - /actuator/**
          - /doc.html
          - /v2/api-docs/**
          - /v3/api-docs/**
          - /swagger-resources/**
          - /swagger-ui/**
          - /webjars/**
          - /bycdao-ui/**
          - /favicon.ico
  swagger:
    title: BallCat-Api Docs
    documentation-type: swagger_2
    description: BallCat 业务接口服务Api文档
    version: 0.0.1
    license: Powered By BallCat
    licenseUrl: http://www.ballcat.cn/
    terms-of-service-url: http://www.ballcat.cn/
    host: http://ballcat-api:9090
    contact:
      name: Hccake
      email: chengbohua@foxmail.com
      url: https://github.com/Hccake
    provider:
      aggregator-origin: http://ballcat-admin:8080
